#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for Salt
# Description: Lists keys of Salt minions
# License:     GPLv2
# Author:      Bo Maryniuk <bo@suse.de>
# Written:     2016 Oct 28
#############################################################

SVER=0.0.1

for RCFILE in $(ls /usr/lib/supportconfig/resources/*.rc); do
    [ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
done

section_header "Supportconfig Plugin for SaltStack, v${SVER}"

check_packages "salt" "salt-master"
plugin_command "salt-key -L"
