#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for Salt
# Description: List Salt jobs
# License:     GPLv2
# Author:      Bo Maryniuk <bo@suse.de>
# Written:     2016 Oct 28
#############################################################

SVER=0.1.0
OF="plugin-saltjobs.txt"

for RCFILE in $(ls /usr/lib/supportconfig/resources/*.rc); do
    [ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
done

check_packages_failhard "salt" "salt-master"
log_entry $OF "Supportconfig Plugin for SaltStack, v${SVER}"
log_cmd $OF "salt-run jobs.list_jobs --out=yaml"
