#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for Salt
# Description: Gathers important troubleshooting information
#              about SaltStack (general)
# License:     GPLv2
# Author:      Bo Maryniuk <bo@suse.de>
# Written:     2016 Oct 28
#############################################################

SVER=0.0.1

for RCFILE in $(ls /usr/lib/supportconfig/resources/*.rc); do
    [ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
done

section_header "Supportconfig Plugin for SaltStack, v${SVER}"
for thisrpm in "salt" "salt-master" "salt-api" "salt-minion" "salt-syndic" "salt-proxy"; do
    validate_rpm_if_installed $thisrpm
done

for i in "salt-master" "salt-api" "salt-minion"; do
    plugin_command "rc$i status"
done

plugin_command "salt-run manage.versions"
